platform :ios,'8.0'
use_frameworks!
target'liwushuo'do
pod 'AFNetworking','~>3.1.0'
pod 'SVProgressHUD', '~> 2.0.3'
#pod 'MJRefresh'
pod 'SDWebImage'
pod 'RealReachability'
pod 'MJExtension'
#pod 'SDCycleScrollView','~> 1.65'
end
